name: Visual Studio

on: [push, pull_request]

jobs:
  build:
    # Skip building pull requests from the same repository
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: qt5
     shell: pwsh
       run: |
        .\qt5.ps1

        
    - name: build
       run:
          cmake -B build
          cmake --build build
