name: GitHub Actions CI
on: [push, pull_request]
jobs:
  Prepare:
    runs-on: windows2019
    
    steps:
      - name: Setup MSVC Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@v2.0.0

      - name: Checkout
        uses: actions/checkout@v2
          submodules:recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
 
        
      - name: Configure
        run:
          cmake -B build
          cmake --build build
