name: GitHub Actions CI
on: [push, pull_request]
jobs:
  Prepare:
    runs-on: windows-latest


      - name: Checkout
        uses: actions/checkout@v2
          submodules:recursive
      

      - name: qt5
       shell: pwsh
         run: |
        .\qt5.ps1

        
      - name: build
        run:
          cmake -B build
          cmake --build build
