name: GitHub Actions CI
on: [push, pull_request]
jobs:
  Prepare:
    runs-on: windows-latest
    
    steps:
      - name: Setup MSVC Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@v2.0.0

      - name: Checkout
        uses: actions/checkout@v2
          submodules:recursive
      

      - name: qt5
       shell: pwsh
         run: |
        .\qt5.ps1

        
      - name: build
        run:
          cmake -B build
          cmake --build build
